### ISSUE TITLE
Bug report: Doesn't export metrics about log files if using timestamps

### ISSUE THREAD

**Issue by theS1LV3R** [gvengel/exim_exporter#32]
If `log_timezone` is set to `true` in exim configuration, the log format changes from

```
YYYY-MM-DD HH:MM:SS MAILID-MAILID-ID flag whatever whatever
```
to
```
YYYY-MM-DD HH:MM:SS +ZZZZ MAILID-MAILID-ID flag whatever whatever
```
(where flag is any of `=>`, `<=`, `**`, `==`, etc etc)

This breaks checking the flags and generating `exim_messages_total` since the index (checked on lines [288-296](https://github.com/gvengel/exim_exporter/blob/main/main.go#L288-L296)) is offset by one.

**Comment by gvengel** [comment]
Thanks for the report. I've verified the issue is reproducible.

**Comment by gvengel** [comment]
Sorry, this got lost behind some feature work, and I should have just shipped it with a patch release... which I've done now with v0.6.2. Thanks again!
