### ISSUE TITLE
Exim internal message ID length changed from 16 to 25 in  4.97 

### ISSUE THREAD

**Issue by ajhstc** [gvengel/exim_exporter#59]
Hello,

Exim changed their message id format in v 4.97 
https://github.com/Exim/exim/blob/79c7bae7b372b89a8051ebc7c850ae9339597949/doc/doc-txt/ChangeLog#L290C1-L290C6

The new ID is 23 characters rather than the previous 16. 

This line prevents message queue from being counted correctly, it might have other implications:
https://github.com/gvengel/exim_exporter/blob/3ca40e81574a7dd02c72a271101023602815e50d/main.go#L222
 
"Quick" fix for us  was to change it to:
`if len(name) == 25 && strings.HasSuffix(name, "-H")`
(could also remove the len check)
and `make build` from source.

**Comment by gvengel** [comment]
Fixed in v0.6.2.
