### ISSUE TITLE
exim container reported issues after exim_exporter setup as sidecar 

### ISSUE THREAD

**Issue by avi-hmcts** [gvengel/exim_exporter#7]
Hi - We have exim running along with fluentbit as sidecar in Kubernetes as a statefulset - https://github.com/luigibk/exim-relay/blob/master/helm/exim/templates/statefulsetOrdeployment.yaml (pvc for /var/spool/exim contents). I have setup exim_exporter as sidecar and noticed that exim(https://github.com/luigibk/exim-relay/blob/master/Dockerfile ) container reported issues(which was fine before introducing exim_exporter as sidecar) - 
> failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "exim -bdf -q15m": executable file not found in $PATH: unknown

Would be good to know if exim_exporter was tested running in k8s and any similar issues found ?

**Comment by gvengel** [comment]
Hey @avi-hmcts,

I only recently added official docker images, so as far as I know, nobody has been using them with kubernetes. 

It seems like the exim binary isn't being found on PATH. I guess it's possible that setting the pid namespace could somehow affect environment variables, but that would be news to me.

Personally, I try to avoid shelling CMD since you can run into weird issues like this. What happens if you call the exim binary directly?

Change:
```Dockerfile
CMD ["exim -bdf -q15m"]
```
to:
```Dockerfile
CMD ["/usr/sbin/exim", "-bdf", "-q15m"]
```

**Comment by avi-hmcts** [comment]
Hey @gvengel ,

Changing it to call the exim binary directly has fixed the container initialisation issues. And I can see both exim and exim_exporter containers are up and running in my pod now. I guess as you mentioned setting the pid namespace is affecting environment variables. Would you know why ?

**Comment by gvengel** [comment]
Well, when you set a pid namespace that changes your pid from `1` (init) to something else. This has a number of side effects, and my theory was that it could somehow prevent the container from adding `/usr/sbin` to `$PATH`. This was just a wild theory though, and after running some tests, I've confirmed that is _not_ the case.

I believe this is really just a bug introduced in this recent commit to your Dockerfile. https://github.com/hmcts/exim-relay/commit/8b1df4c6715b23c5dfaa14409ccc7c57a46c2ca9#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R41

You can see the use of `CMD` attempts to change from the _exec_ form to the _shell_ form; however, you would need to remove the braces to do so correctly. See https://docs.docker.com/engine/reference/builder/#cmd for reference.
