### ISSUE TITLE
exim-exporter doesn't collect the metrics

### ISSUE THREAD

**Issue by avi-hmcts** [gvengel/exim_exporter#8]
Hi @gvengel - This is in continuation to what has been raised sometime ago https://github.com/gvengel/exim_exporter/issues/7 . Even though exim-exporter container initialisation issues were fixed as discussed but it fails to serve it's purpose i.e. to extract metrics from the running exim container (exim-exporter has been configured to run as a sidecar and was setup successfully with the mounted volumes for **/var/spool/exim** and **/var/log/exim**). 

I have been able to successfully set up exim-exporter as the scraping target for Prometheus but don't see **exim_up** metric (which should always return 1 as it's the main exim daemon but returns 0) let alone the other metrics i.e. **exim_log_read_errors**, **exim_queue**, **exim_reject_total**, **exim_panic_total** even though there has been sufficient traffic going through exim.  **exim_exporter_build_info** metric always returns value 1.

Let me know if you need more info but any pointers to fix the issue would be great.

**Comment by gvengel** [comment]
Are you setting `shareProcessNamespace: true` in your pod which contains both the exim and exim_exporter containers? 

Full disclosure, I do not use kubernetes, so I could be giving you bad information. Basically, you need to map my example with docker to the kubernetes equivalent.

```
docker run 
  -p 9636:9636 \
  -v /var/log/exim4:/var/log/exim4 \
  -v /var/spool/exim4:/var/spool/exim4 \
  --pid container:exim4 \
  --name exim_exporter \
  gvengel/exim_exporter
```
or
https://github.com/gvengel/exim_exporter/blob/master/docker-compose.yml

If you can't get it working, I can try to find some time to stand up a k8s test instance and debug, but no promises.

**Comment by avi-hmcts** [comment]
I have tried with `shareProcessNamespace: true` on the exim statefulset but that doesn't seem to work as I still can't see the `exim_up` returning 1 (as the exim container has no issues running).  It would be great if you could validate on a k8s test instance as this would be a common approach for anyone using Prometheus on their k8s clusters (as this would be a blocker to use **exim-exporter** as a sidecar running in k8s). I don't think there would be many use cases to use this running as a stand alone docker container.

**Comment by avi-hmcts** [comment]
Thanks @gvengel.

**Comment by gvengel** [comment]
@avi-hmcts This should be fixed in version 1.3.1. Let me know if are still seeing issues. Thanks!

**Comment by avi-hmcts** [comment]
I just checked your changes to fix this. Would this only work if the daemon process is **/use/sbin/exim4** and not with **/usr/sbin/exim** ?

**Comment by gvengel** [comment]
Yes, all of the process stats rely on knowing the name of the exim binary, and the `exim_up` metric is just a special process stat which only counts the main exim daemon process. By default it's looking for `exim4`; however, you can override it to whatever value is right for your system with the `--exim.executable` CLI flag. All of the flags also support configuration via environment variable for Docker.

So in your case, you'll want something like:

```yaml
    - name: exporter
      image: gvengel/exim_exporter
      env:
        - name: EXIM_EXECUTABLE
          value: exim
```

You many need to make a few other adjustments depending on your exim server configuration. See `exim_exporter --help` for more detail.

**Comment by avi-hmcts** [comment]
sure @gvengel I will have a look ...I have just pulled in the latest and tried running a docker build (after `go build`)and strangely (because it's windows related and I'm running on a MacbookPro)see the errors below :- 

```
[+] Building 1.8s (9/13)                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 37B                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/golang:buster                                                                          0.8s
 => [builder 1/8] FROM docker.io/library/golang:buster@sha256:ab32429d40c1b734ed4f036838ac516352182f9414563478fa88a1553c4a4414            0.0s
 => [internal] load build context                                                                                                         0.3s
 => => transferring context: 13.25MB                                                                                                      0.3s
 => CACHED [builder 2/8] WORKDIR /src                                                                                                     0.0s
 => CACHED [builder 3/8] COPY . .                                                                                                         0.0s
 => CACHED [builder 4/8] RUN apt update && apt install -y dpkg-dev git                                                                    0.0s
 => ERROR [builder 5/8] RUN go test -v .                                                                                                  0.6s
------
 > [builder 5/8] RUN go test -v .:
#7 0.612 go: github.com/StackExchange/wmi@v0.0.0-20210224194228-fe8f1750fd46: Get "https://proxy.golang.org/github.com/%21stack%21exchange/wmi/@v/v0.0.0-20210224194228-fe8f1750fd46.mod": x509: certificate signed by unknown authority
------
executor failed running [/bin/sh -c go test -v .]: exit code: 1
```

**Comment by gvengel** [comment]
Huh, not sure on that one. All my builds worked fine, both with Docker Desktop on MacOS and through TravisCI. 

The latest build is published on Docker Hub via TravisCI, so you should be able to use that without building locally. e.g. `docker pull gvengel/exim_exportor` should pull down 1.3.1, or you can specify the tag explicitly.

**Comment by gvengel** [comment]
Did you get everything worked out?

**Comment by avi-hmcts** [comment]
@gvengel - sorry for getting back late on this as we wanted to evaluate all possible options before I get back to you on the eximexporter container config in our deployment.yaml. `exim_up` wasn't still retrieving the value 1 after specifying the env variable `exim_executable` as `exim` so we had to modify the path to `/usr/bin/exim` in the exim_exporter GO code and built a new tag for it which resolved the issue. Thanks

**Comment by gvengel** [comment]
Thanks for the update, @avi-hmcts. I'm glad you got everything working, but that setting should have worked. I'll set up a couple tests to make sure we don't have another bug lurking in there.
